namespace Aelvory.Server.Entities;

/// <summary>
/// Refresh token row. The plaintext token is generated by
/// <c>JwtTokenService.GenerateRefreshToken</c> and handed to the
/// client; only the <see cref="TokenHash"/> is stored at rest, so a
/// read-only DB compromise (backup leak, errant log, future SQLi)
/// can't be replayed as live sessions. Rotation: each Refresh()
/// call sets <see cref="RevokedAt"/> on the consumed row and issues
/// a new one.
/// </summary>
public class RefreshToken
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public User User { get; set; } = null!;
    /// <summary>
    /// SHA-256 of the raw 64-byte refresh token. Hex-encoded
    /// (lowercase) so the column is human-readable in DB tooling
    /// and indexable. We don't pepper / use Argon2 here because the
    /// raw token is already 512 bits of entropy — fast hash is
    /// fine; the security property we need is "DB read can't
    /// recover the token," not "user can pick a weak token."
    /// </summary>
    public required string TokenHash { get; set; }
    public DateTime ExpiresAt { get; set; }
    public DateTime? RevokedAt { get; set; }
    public DateTime CreatedAt { get; set; }
}
